### ISSUE TITLE
Compile Error App\Model\IcalEvent::__toString() must be public

### ISSUE THREAD

**Issue by MultiTricker** [petrbrouzda/IcalTransformer#1]
Ahoj,

po instalaci jsem dostal chybu:
`Compile Error: Access level to App\Model\IcalEvent::__toString() must be public (as in class Stringable) in /var/www/clients/client136/web378/web/app/Model/IcalEvent.php:63`

Po změně viditelnosti metody na public vše frčí a eventy z kalendáře vrací. Vyzkoušeno na PHP 8.0.

Díky za skvělou práci!

**Comment by petrbrouzda** [comment]
Jo, já jedu ještě na PHP 7.x.
Opraveno, dík.
